package:
  version: "{{ load_setup_py_data().version }}"
  name: 'pycydemo'

source:
  path: ../../

build:
  number: 0
  script: python setup.py install

requirements:
  build:
    - python
    - numpy
    - cython >=0.24.1
    - setuptools
    - nose
    - gcc
  run:
    - python
    - numpy
    - nose
    - libgcc

about:
  description: Demo python+cython project
  home: https://github.com/theochem/python-cython-ci-example
  license: MIT

extra:
  recipe-maintainers: Toon Verstraelen <toon.verstraelen@gmail.com>
